# EUREKA CONFIGURATION
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
# ACTUATOR CONFIGURATION
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - '*'
# LOGGING CONFIGURATION        
logging:
  file:
    name: /Users/PC/Documents/workspace-spring-tools-for-eclipse-4.31.0.RELEASE/ECOMMERCE/centralized_logs/microservices.log
