# EUREKA CONFIGURATION
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
# ACTUATOR CONFIGURATION
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - '*'
# LOGGING CONFIGURATION        
logging:
  file:
    name: /Users/TEMP/Desktop/SPRING_BOOT_PROJECT/EUREKA_GATEWAY_CONFIG_ZIPKIN_SLEUTH_ELK/centralized_logs/microservices.log        
